server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    accesslog:
      buffered: true
      directory: /home/log/tomcat
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%t | %{X-Real-IP}i | %b | %B | %H | %l | %m | %p | %q | %r | %s | %S | %u | %U | %v | %D | %T | %{Cookie}i | %{User-Agent}i | %{a}r'
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
spring:
  application:
    name: support
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/music?serverTimezone=GMT%2B8
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    http:
      encoding:
        force: true
        charset: utf-8
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.game.www
  # spring boot集成mybatis的方式打印sql，需要使用的话可以开启
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml
  level:
    com.tyy.ss: debug


qmkg:
  userAttr:
    619f94812d2e328e32:
      id: 619f94812d2e328e32
      singer: 赖琼芳
    63999887222f3f8235:
      id: 63999887222f3f8235
      singer: 赖琼芳
    659c9f85222935883d:
      id: 659c9f85222935883d
      singer: 谭礼珠